### ISSUE TITLE
Editing Tweaks in Prime 2 (Trilogy) causes game to crash upon booting

### ISSUE THREAD

**Issue by SubsonicBeatz154** [arukibree/PrimeWorldEditor#10]
I tried to edit some of the tweaks in Prime 2 (Trilogy version) and the game crashes upon booting now... Even after reverting the tweaks the game still crashes upon booting, this isn't happening with my non-modified dump. Tested in v1.2.3.

**Comment by arukibree** [comment]
By reverting the tweaks, do you mean you restored the original Standard.ntwk file? Or do you mean you changed the property values back to what they originally were in the editor? If the former, then that seems strange.

I can't 100% guarantee full compatibility with the Trilogy versions - the property layouts I have are for the GameCube version and I haven't checked whether anything has been changed for Trilogy. Plus versioning support for script templates is dicey-to-nonexistant. It's possible some properties were added or removed in Trilogy (though I wouldn't think that alone would cause the game to crash). If this is the case, then there are probably some log messages about unrecognized property IDs.

**Comment by SubsonicBeatz154** [comment]
I just changed to property values back to what they were originally in the editor, i'll try restoring that Standard.ntwk file and see if that fixes things.

**Comment by SubsonicBeatz154** [comment]
OK, restoring the original Standard.ntwk file fixed it! Thanks!
