### ISSUE TITLE
Compile errors - "libcommon"

### ISSUE THREAD

**Issue by mlabbe** [arukibree/PrimeWorldEditor#5]
Building in QtCreator has it looking for relative directory `LibCommon` which doesn't seem to exist.

> 15:55:55: Running steps for project PrimeWorldEditor...
> 15:55:55: Starting: "J:\dev\vendors\qt\5.9.1\msvc2015_64\bin\qmake.exe" J:\dev\vendors\PrimeWorldEditor\src\PrimeWorldEditor.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
> Info: creating stash file J:\dev\vendors\PrimeWorldEditor\build-PrimeWorldEditor-Desktop_Qt_5_9_1_MSVC2015_64bit-Debug\.qmake.stash
> 15:55:55: The process "J:\dev\vendors\qt\5.9.1\msvc2015_64\bin\qmake.exe" exited normally.
> 15:55:55: Starting: "J:\dev\vendors\qt\Tools\QtCreator\bin\jom.exe" qmake_all
> 
> jom 1.1.2 - empower your cores
> 
> 	cd ..\externals\LibCommon\Source\ && J:\dev\vendors\qt\5.9.1\msvc2015_64\bin\qmake.exe -o Makefile.LibCommon J:\dev\vendors\PrimeWorldEditor\externals\LibCommon\Source\LibCommon.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
> Info: creating stash file J:\dev\vendors\PrimeWorldEditor\externals\LibCommon\Source\.qmake.stash
> Cannot read J:/dev/vendors/PrimeWorldEditor/externals/LibCommon/Externals/CodeGen/codegen.pri: No such file or directory
> WARNING: Failure to find: J:/dev/vendors/PrimeWorldEditor/externals/LibCommon/Source/../Externals/tinyxml2/tinyxml2.cpp
> WARNING: Failure to find: J:/dev/vendors/PrimeWorldEditor/externals/LibCommon/Source/../Externals/tinyxml2/tinyxml2.cpp
> 	cd ..\externals\LibCommon\Source\ && J:\dev\vendors\qt\Tools\QtCreator\bin\jom.exe -f Makefile.LibCommon qmake_all
> 	cd Core\ && J:\dev\vendors\qt\5.9.1\msvc2015_64\bin\qmake.exe -o Makefile J:\dev\vendors\PrimeWorldEditor\src\Core\Core.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
> WARNING: Failure to find: J:\dev\vendors\PrimeWorldEditor\externals\lzo-2.10\src\lzo_init.c
> WARNING: Failure to find: J:\dev\vendors\PrimeWorldEditor\externals\lzo-2.10\src\lzo1x_9x.c
> WARNING: Failure to find: J:\dev\vendors\PrimeWorldEditor\externals\lzo-2.10\src\lzo1x_d1.c
> WARNING: Failure to find: J:\dev\vendors\PrimeWorldEditor\externals\lzo-2.10\src\lzo_init.c
> WARNING: Failure to find: J:\dev\vendors\PrimeWorldEditor\externals\lzo-2.10\src\lzo1x_9x.c
> WARNING: Failure to find: J:\dev\vendors\PrimeWorldEditor\externals\lzo-2.10\src\lzo1x_d1.c
> 	cd Core\ && J:\dev\vendors\qt\Tools\QtCreator\bin\jom.exe -f Makefile qmake_all
> 	cd Editor\ && J:\dev\vendors\qt\5.9.1\msvc2015_64\bin\qmake.exe -o Makefile J:\dev\vendors\PrimeWorldEditor\src\Editor\Editor.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
> 	cd Editor\ && J:\dev\vendors\qt\Tools\QtCreator\bin\jom.exe -f Makefile qmake_all
> 15:55:59: The process "J:\dev\vendors\qt\Tools\QtCreator\bin\jom.exe" exited normally.
> 15:55:59: Starting: "J:\dev\vendors\qt\Tools\QtCreator\bin\jom.exe" 
> 	cd ..\externals\LibCommon\Source\ && ( if not exist Makefile.LibCommon J:\dev\vendors\qt\5.9.1\msvc2015_64\bin\qmake.exe -o Makefile.LibCommon J:\dev\vendors\PrimeWorldEditor\externals\LibCommon\Source\LibCommon.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && J:\dev\vendors\qt\Tools\QtCreator\bin\jom.exe -f Makefile.LibCommon
> 	J:\dev\vendors\qt\Tools\QtCreator\bin\jom.exe -f Makefile.LibCommon.Debug
> Error: dependent 'J:\dev\vendors\PrimeWorldEditor\externals\LibCommon\Source\..\Externals\tinyxml2\tinyxml2.cpp' does not exist.
> jom: J:\dev\vendors\PrimeWorldEditor\externals\LibCommon\Source\Makefile.LibCommon [debug] Error 2
> jom: J:\dev\vendors\PrimeWorldEditor\build-PrimeWorldEditor-Desktop_Qt_5_9_1_MSVC2015_64bit-Debug\Makefile [sub----externals-LibCommon-Source-LibCommon-pro-make_first-ordered] Error 2
> 15:55:59: The process "J:\dev\vendors\qt\Tools\QtCreator\bin\jom.exe" exited with code 2.
> Error while building/deploying project PrimeWorldEditor (kit: Desktop Qt 5.9.1 MSVC2015 64bit)
> When executing step "Make"
> 15:55:59: Elapsed time: 00:04.

**Comment by arukibree** [comment]
Sounds like you need to run `git update submodule --recursive`. Though it still won't compile then since the zlib and LZO submodules are legitimately missing from the repo - hopefully I should have time to fix that tonight

**Comment by mlabbe** [comment]
I did that prior to running the build that failed above.  It will still fail.

`PrimeWorldEditor\externals\tinyxml2\tinyxml2.cpp` is the path to tinyxml2.cpp at compile time.  Are you depending on files that have been moved locally in order to build correctly?

**Comment by arukibree** [comment]
No, LibCommon has its own externals directory, one of which is is tinyxml2. The error sounds like you don't have LibCommon's externals. The version of tinyxml2 in PWE's externals folder I don't think is used anymore, probably needs to be removed.

**Comment by arukibree** [comment]
Oh that one seems strange, not 100% sure. I'll look into it soon.

**Comment by arukibree** [comment]
I think the submodule issues should be fixed, and there's also been information about other build requirements added to the readme. Let me know if you're able to compile now. I will try to compile from a fresh clone of the repository to make sure it works soon.

**Comment by mlabbe** [comment]
On one hand I don't want to be entitled and demand you simplify your build process -- I am an open source maintainer and I understand that your time is yours to give.

On the other hand, I don't have the time to follow through the build instructions you've posted.  Sorry.

**Comment by arukibree** [comment]
Ok, closing issue then as others have been able to compile.

**Comment by sfuller** [comment]
@mlabbe For what it's worth, I'm working on some build features that should make this project easier for others to build. Stay tuned!
