### ISSUE TITLE
PWE Crashes When Tools -> Edit Layers is Opened

### ISSUE THREAD

**Issue by Robospot** [arukibree/PrimeWorldEditor#7]
**Date Tested:** 2/17/2019
**PWE Version:** v1.2.2
**Steps to Recreate:** Open PWE v1.2.2 and without opening a project go to the Tools dropdown and click Edit Layers.
[primeworldeditor.log](https://github.com/arukibree/PrimeWorldEditor/files/2873131/primeworldeditor.log)

**Comment by arukibree** [comment]
Fixed in d9f149360e8e9b4e9ab1aa4f3a015ec25554bfcc
