### ISSUE TITLE
PWE Crashes When Exporting An Asset Name Map

### ISSUE THREAD

**Issue by Robospot** [arukibree/PrimeWorldEditor#8]
**Date Tested:** 2/17/2019
**PWE Version:** v1.2.2
**Steps to Recreate:** Open PWE v1.2.2 and without opening a project click on the gear dropdown and select Export Names. File explorer will open up allowing you to enter a name for the exported asset map. Simply type a random word and click save. PWE should crash.
[primeworldeditor.log](https://github.com/arukibree/PrimeWorldEditor/files/2873138/primeworldeditor.log)

**Comment by arukibree** [comment]
Fixed in d9f149360e8e9b4e9ab1aa4f3a015ec25554bfcc
